export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Resume',
    headline: '',
    description: 'From dancing and creating art, to building applications and choreographing code; I am a dancer turned software developer aspiring to have a positive impact on the world using technology.',
    buttonLabel: 'More Info about',
    imgStart: false,
    img: require('../../Images/png-1.png'),
    alt: 'svg',
    dark: true,
    primary: true,
    darkText: false,
} 

export const homeObjTwo = {
    id: 'skills',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Skills',
    headline: '',
    description: 'Los textos informativos brindan descripciones y datos sobre la realidad, sin incluir las emociones, opiniones, puntos de vista o deseos de su emisor.  Pueden aludir a hechos actuales o pasados.',
    buttonLabel: 'More Info skills',
    imgStart: true,
    img: require('../../Images/Logok.png'),
    alt: 'svg',
    dark: false,
    primary: false,
    darkText: true,
} 

export const homeObjThree = {
    id: 'projects',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Projects',
    headline: 'Traveling the world in 80 Days',
    description: 'In this game you will have the opportunity to travel and learn more about the culture and traditions of differents countries. To achive this, you will have to take decisions and choose what things you want to know and from where.',
    buttonLabel: 'More Info projects',
    imgStart: false,
    img: require('../../Images/png-1.png'),
    alt: 'svg',
    dark: true,
    primary: true,
    darkText: false,
} 